version: '3.7'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app/
#      - /home/magomed/master/new/sherlock-docs/Dataset:/usr/src/app/media/docs/Dataset

    ports:
      - 8020:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    restart: unless-stopped
    networks:
      - sherlock-docs-backend-tier
    depends_on:
      - db
      - redis

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    networks:
      - sherlock-docs-backend-tier
    volumes:
      - sherlock-docs-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  celery:
    build: ./project
    command: celery worker --app=core --loglevel=info
    volumes:
      - ./project:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    networks:
      - sherlock-docs-backend-tier
    depends_on:
      - web
      - redis

  redis:
    image: redis:5-alpine
    ports:
    - "127.0.0.1:6379:6379"
    networks:
      - sherlock-docs-backend-tier
    volumes:
      - sherlock-docs-redis:/data

volumes:
  sherlock-docs-db:
    driver: local
  sherlock-docs-redis:
    driver: local

networks:
  sherlock-docs-backend-tier:
    driver: bridge