# Generated by Django 3.1.1 on 2020-10-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs', verbose_name='Оригинальный файл документа')),
                ('status', models.CharField(choices=[('Q', 'В очереди'), ('P', 'В процессе'), ('C', 'Распознан')], default='Q', max_length=1, verbose_name='Статус распознавания')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
