# Generated by Django 3.0.4 on 2020-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации)'),
        ),
    ]
