# Generated by Django 3.0.4 on 2020-10-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_document_full_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='full_text',
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации) через OCR'),
        ),
        migrations.AddField(
            model_name='document',
            name='tesseract_text',
            field=models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации) через Tesseract'),
        ),
    ]
