# Generated by Django 3.0.4 on 2020-10-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20201005_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-id'], 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документов'},
        ),
    ]
