# Generated by Django 3.0.4 on 2020-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20201026_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_text',
            field=models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации) через Antiword или '),
        ),
    ]
