# Generated by Django 3.0.4 on 2020-10-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_document_doc_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(default=1, verbose_name='Номер страницы')),
                ('file', models.FileField(upload_to='docs/pages', verbose_name='Постраничный файл документа')),
                ('status', models.CharField(choices=[('Q', 'В очереди'), ('P', 'В процессе'), ('C', 'Распознан')], default='Q', max_length=1, verbose_name='Статус распознавания')),
                ('ocr_text', models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации) через OCR')),
                ('tesseract_text', models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации) через Tesseract')),
                ('doc_text', models.TextField(blank=True, null=True, verbose_name='Распознанный текст из документа(без сегментации) через Antiword или ')),
                ('parent_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr.Document', verbose_name='Основной документ')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.DocumentType', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Страница из документа',
                'verbose_name_plural': 'Страницы из документов',
                'ordering': ['-id'],
            },
        ),
    ]
