# Generated by Django 3.0.4 on 2020-10-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_pagedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default=1, max_length=255, verbose_name='Временный тип файлов'),
            preserve_default=False,
        ),
    ]
