# Generated by Django 3.0.4 on 2020-10-31 08:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_auto_20201031_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalizedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Распознанный текст')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Атрибуты документа')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formalized_docs', to='ocr.PageDocument', verbose_name='Родитель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formalized_docs', to='ocr.DocumentType', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Формализованный документ',
                'verbose_name_plural': 'Формализованные документы',
            },
        ),
        migrations.AddField(
            model_name='pagedocument',
            name='jpg_file',
            field=models.FileField(default=1, upload_to='docs/pages/jpg', verbose_name='Постраничный файл документа'),
            preserve_default=False,
        ),
    ]
