# Generated by Django 3.0.4 on 2020-10-31 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_formalizeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Атрибуты'),
        ),
    ]
