# Generated by Django 3.0.4 on 2020-10-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_auto_20201031_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='tesseract_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='pagedocument',
            old_name='tesseract_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ocr_text',
        ),
        migrations.RemoveField(
            model_name='pagedocument',
            name='ocr_text',
        ),
    ]
